site_name: TOKEO 日本語
site_url: https://btbf.github.io/tokeo-jp/
site_description: Tokeoは、安全、安心、そして機能満載の、Cardano以降の次世代スマート・モバイル・ウォレットです。BitcoinやEVMベースのチェーンとシームレスにリンクするクロスチェーンサービスへと迅速に移行する予定です。
theme:
  language: ja
  favicon: images/tokeo_logo400x400.jpg
  logo: images/tokeo_logo400x400.jpg
  font:
    text: Noto Sans JP
  name: material
  custom_dir: docs/overrides
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      accent: cyan
      primary: custom
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  features:
    - content.tabs.link
    - navigation.indexes
    - navigation.top
    - navigation.instant
    - navigation.tracking
    - navigation.footer
    - navigation.path
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy
    - content.code.annotate
  icon:
    repo: fontawesome/brands/github

copyright: Copyright &copy; 2024 BTBF

plugins:
  - git-revision-date-localized:
      type: datetime
  - search:
      lang: ja

extra:
  generator: false
  analytics:
    provider: google
    property: G-TX4FW9W9LT
  consent:
    title: Cookieの使用許諾
    description: >- 
      当サイトは、ドキュメントの効果測定や利用者確認のため、クッキーを使用しGoogle アナリティクスによるトラフィックの分析を行っています。
      ご同意いただける場合は「Accept」をクリックしてください。

    cookies:
      analytics: Google Analytics


markdown_extensions:
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - attr_list
  - md_in_html
  - toc:
      permalink: true
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

extra_css:
  - stylesheets/extra.css

nav:
  - 'TOKEO': 
    - './index.md'
    - 'アセット交換': './asset-swap.md'
    - 'コレクション': './collectibles.md'
    - '支払い機能': './payments.md'
    - 'ロードマップ': './roadmap.md'
    - 'チームについて': './our-team.md'
  - 'トケノミクス':
    - './tokenomics.md'
    - 'トークン割当': './distribution.md'
    - '権利確定': './vesting.md'
    - 'ユーティリティ': './utillity.md'
  - 'ISPO':
    - 'ispo.md'
    - 'TOKEO ISPOについて': './tokeo-ispo.md'
    - 'トークン配布': './token-distribution.md'
    - 'パートナーSPO': './partner-spos.md'
    - '報酬': './rewards.md'
  - '公式リンク':
     - './official-link.md'
  - 'Support':
     - './support.md'